// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqGAthgdDQe1u3LR9HO0LDmKAZPMlOy04',
    appId: '1:606447212038:web:3dc109b3bb8959cf119587',
    messagingSenderId: '606447212038',
    projectId: 'fir-authentication-2ad0a',
    authDomain: 'fir-authentication-2ad0a.firebaseapp.com',
    storageBucket: 'fir-authentication-2ad0a.firebasestorage.app',
    measurementId: 'G-BFJYJ3JX1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK50ntru6i4tIC8MYEGlrlXn_zhXHA8j8',
    appId: '1:606447212038:android:abd730a33b6a0174119587',
    messagingSenderId: '606447212038',
    projectId: 'fir-authentication-2ad0a',
    storageBucket: 'fir-authentication-2ad0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCnYmh52hKLqXka7XBFdlDVhpPAxJLA8o',
    appId: '1:606447212038:ios:52dba31635365437119587',
    messagingSenderId: '606447212038',
    projectId: 'fir-authentication-2ad0a',
    storageBucket: 'fir-authentication-2ad0a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCnYmh52hKLqXka7XBFdlDVhpPAxJLA8o',
    appId: '1:606447212038:ios:52dba31635365437119587',
    messagingSenderId: '606447212038',
    projectId: 'fir-authentication-2ad0a',
    storageBucket: 'fir-authentication-2ad0a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqGAthgdDQe1u3LR9HO0LDmKAZPMlOy04',
    appId: '1:606447212038:web:6afe03fa624f85f8119587',
    messagingSenderId: '606447212038',
    projectId: 'fir-authentication-2ad0a',
    authDomain: 'fir-authentication-2ad0a.firebaseapp.com',
    storageBucket: 'fir-authentication-2ad0a.firebasestorage.app',
    measurementId: 'G-DGRJFJ51DM',
  );
}
